### PR TITLE
refactor: update module

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
- Update module following [module-template](https://github.com/nuxt-community/module-template)
- Coverage works again :smile: 
- Update dependency `localforage` to `^1.7.3`
- Add new method `dropInstance`
- Add new option `instances`
- Resolve #5

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
ping @nuxt-community/core-team

**Comment by WhiteR4bbitt** [comment]
Anything on this? Looking at it, this is a huge upgrade from where the module sits now, would love to update the package to this! :)

**Comment by ricardogobbosouza** [comment]
@WhiteR4bbitt I didn't have more answers

**Comment by ricardogobbosouza** [comment]
ping @alexchopin

**Comment by WhiteR4bbitt** [comment]
> @WhiteR4bbitt I didn't have more answers

All good @ricardogobbosouza, I updated my `package.json` version reference to `ricardogobbosouza/localforage-module#update-module` for the branch from your PR and its working fine, I can report any issues if I encounter any.

**Comment by WhiteR4bbitt** [comment]
I didn't realize this at the time (kind of getting over a head cold), but the package version wasn't updated so we can't properly call the new version. Anyway to quickly get that updated or should a new PR be opened for it?

**Pull request merged**
